---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: kube-system
  name: grafana-dashboard-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-dashboard-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: grafana-dashboard-account
    namespace: kube-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-dashboard-operator
  namespace: kube-system
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      application: grafana-dashboard-operator
  template:
    metadata:
      labels:
        application: grafana-dashboard-operator
    spec:
      serviceAccountName: grafana-dashboard-account
      containers:
      - name: grafana-dashboard-operator
        image: registry.grofer.io/infra/legend:master
        resources:
          limits:
            cpu: 200m
            memory: 300Mi
          requests:
            cpu: 150m
            memory: 250Mi
        imagePullPolicy: Always
        env:
          - name: GRAFANA_API_KEY
            valueFrom:
              secretKeyRef:
                name: grafana-dashboards-conf
                key: api_key
          - name: GRAFANA_HOST
            valueFrom:
              secretKeyRef:
                name: grafana-dashboards-conf
                key: host
          - name: GRAFANA_PROTOCOL
            valueFrom:
              secretKeyRef:
                name: grafana-dashboards-conf
                key: protocol
